### ISSUE TITLE
Add runtime version (or customizable title)

### ISSUE THREAD

**Issue by rynowak** [Tyrrrz/GitHubActionsTestLogger#8]
I've been testing out this project (works great btw 👍) and I think one thing that's missing is including the framework/runtime version in the annotation. I wanted to start a discussion here, first of all to say thanks for a great project 👏 👏 👏 - and in case anyone else ran into the same thing.

I'm in a situation where I need to test both netcoreapp3.1 and net5 and I don't want to be confusing to people why they see the same error reported twice:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/1430011/107897109-2ad77580-6eed-11eb-80f2-b87561afa81d.png">

----

It would be great if there was an option to include the runtime version, or if not to find some strategy where I could customize this. For instance right now I'm not specifying a target framework at the command line, and letting `dotnet test` do its magic. I could easily change this if it makes the error reporting experience better.

One of the ideas here would be to use a matrix and make that part of the job name. 

Example:

```yaml
test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [3.1.x, 5.0.x]

    name: Test ${{ matrix.dotnet-version }}
```
